### ISSUE TITLE
webstore page does not give justification google.com data access

### ISSUE THREAD

**Issue by nocnokneo** [adamzr/RSS-Alert#1]
The download page in the Chrome webstore should give an explanation for why the extension needs access to your data on www.google.com and ajax.googleapis.com.

**Comment by ghost** [comment]
He's using the google feed API to load the rss feed.  I suppose it wouldn't hurt to say that on the webstore page.

**Comment by adamzr** [comment]
Yes, I use the Google Feed API. I also download jQuery from Google. I added mention of this to the WebStore description. Thanks!
