### ISSUE TITLE
Can't add feed?

### ISSUE THREAD

**Issue by iaing80** [adamzr/RSS-Alert#5]
http://www.cityofpeterboroughhockeyclub.co.uk/news/feed

Add the above feed (which works in google reader) to the extension but it will not add??

Sorry if I am missing some thing??

**Comment by adamzr** [comment]
That is strange because when I tried it did add:
![Screenshot](http://i.imgur.com/vv67R.png)
![Popup screenshot](http://i.imgur.com/2GNbu.png)

I can't think of a reason why it would work in mine, but not in yours. What version of Chrome and what OS are you using?

**Comment by iaing80** [comment]
Blimey that was quick!

I apologise as soon as I went to find out what version of chrome I was using
it asked to close to update.  Now updated it adds the feed correctly.

Thanks

Iain

**Comment by adamzr** [comment]
Glad it works now!
